/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HAMSTER_H_RPCGEN
#define _HAMSTER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct hamster_new_arg {
	char owner[32];
	char hamster[32];
	short treats;
};
typedef struct hamster_new_arg hamster_new_arg;

struct hamster_lookup_arg {
	char owner[32];
	char hamster[32];
};
typedef struct hamster_lookup_arg hamster_lookup_arg;

struct hamster_directory_arg {
	int fdptr;
	char owner[32];
	char hamster[32];
};
typedef struct hamster_directory_arg hamster_directory_arg;

struct hamster_directory_ret {
	int res;
	int fdptr;
};
typedef struct hamster_directory_ret hamster_directory_ret;

struct hamster_howsdoing_ret {
	int res;
	short treats_left;
	int rounds;
	short cost;
};
typedef struct hamster_howsdoing_ret hamster_howsdoing_ret;

struct hamster_readentry_ret {
	int res;
	char owner[32];
	char hamster[32];
	short price;
};
typedef struct hamster_readentry_ret hamster_readentry_ret;

struct hamster_givetreats_arg {
	int ID;
	short treats;
};
typedef struct hamster_givetreats_arg hamster_givetreats_arg;

struct hamster_collect_arg {
	char owner[32];
};
typedef struct hamster_collect_arg hamster_collect_arg;

#define HAMSTER_RPC 0x2345121
#define HAMSTER 1

#if defined(__STDC__) || defined(__cplusplus)
#define HAMSTER_NEW 1
extern  int * hamster_new_1(hamster_new_arg *, CLIENT *);
extern  int * hamster_new_1_svc(hamster_new_arg *, struct svc_req *);
#define HAMSTER_LOOKUP 2
extern  int * hamster_lookup_1(hamster_lookup_arg *, CLIENT *);
extern  int * hamster_lookup_1_svc(hamster_lookup_arg *, struct svc_req *);
#define HAMSTER_DIRECTORY 3
extern  hamster_directory_ret * hamster_directory_1(hamster_directory_arg *, CLIENT *);
extern  hamster_directory_ret * hamster_directory_1_svc(hamster_directory_arg *, struct svc_req *);
#define HAMSTER_HOWSDOING 4
extern  hamster_howsdoing_ret * hamster_howsdoing_1(int *, CLIENT *);
extern  hamster_howsdoing_ret * hamster_howsdoing_1_svc(int *, struct svc_req *);
#define HAMSTER_READENTRY 5
extern  hamster_readentry_ret * hamster_readentry_1(int *, CLIENT *);
extern  hamster_readentry_ret * hamster_readentry_1_svc(int *, struct svc_req *);
#define HAMSTER_GIVETREATS 6
extern  int * hamster_givetreats_1(hamster_givetreats_arg *, CLIENT *);
extern  int * hamster_givetreats_1_svc(hamster_givetreats_arg *, struct svc_req *);
#define HAMSTER_COLLECT 7
extern  int * hamster_collect_1(hamster_collect_arg *, CLIENT *);
extern  int * hamster_collect_1_svc(hamster_collect_arg *, struct svc_req *);
extern int hamster_rpc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HAMSTER_NEW 1
extern  int * hamster_new_1();
extern  int * hamster_new_1_svc();
#define HAMSTER_LOOKUP 2
extern  int * hamster_lookup_1();
extern  int * hamster_lookup_1_svc();
#define HAMSTER_DIRECTORY 3
extern  hamster_directory_ret * hamster_directory_1();
extern  hamster_directory_ret * hamster_directory_1_svc();
#define HAMSTER_HOWSDOING 4
extern  hamster_howsdoing_ret * hamster_howsdoing_1();
extern  hamster_howsdoing_ret * hamster_howsdoing_1_svc();
#define HAMSTER_READENTRY 5
extern  hamster_readentry_ret * hamster_readentry_1();
extern  hamster_readentry_ret * hamster_readentry_1_svc();
#define HAMSTER_GIVETREATS 6
extern  int * hamster_givetreats_1();
extern  int * hamster_givetreats_1_svc();
#define HAMSTER_COLLECT 7
extern  int * hamster_collect_1();
extern  int * hamster_collect_1_svc();
extern int hamster_rpc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_hamster_new_arg (XDR *, hamster_new_arg*);
extern  bool_t xdr_hamster_lookup_arg (XDR *, hamster_lookup_arg*);
extern  bool_t xdr_hamster_directory_arg (XDR *, hamster_directory_arg*);
extern  bool_t xdr_hamster_directory_ret (XDR *, hamster_directory_ret*);
extern  bool_t xdr_hamster_howsdoing_ret (XDR *, hamster_howsdoing_ret*);
extern  bool_t xdr_hamster_readentry_ret (XDR *, hamster_readentry_ret*);
extern  bool_t xdr_hamster_givetreats_arg (XDR *, hamster_givetreats_arg*);
extern  bool_t xdr_hamster_collect_arg (XDR *, hamster_collect_arg*);

#else /* K&R C */
extern bool_t xdr_hamster_new_arg ();
extern bool_t xdr_hamster_lookup_arg ();
extern bool_t xdr_hamster_directory_arg ();
extern bool_t xdr_hamster_directory_ret ();
extern bool_t xdr_hamster_howsdoing_ret ();
extern bool_t xdr_hamster_readentry_ret ();
extern bool_t xdr_hamster_givetreats_arg ();
extern bool_t xdr_hamster_collect_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HAMSTER_H_RPCGEN */
