/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hamster.h"

bool_t
xdr_hamster_new_arg (XDR *xdrs, hamster_new_arg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->owner, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hamster, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->treats))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hamster_lookup_arg (XDR *xdrs, hamster_lookup_arg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->owner, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hamster, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hamster_directory_arg (XDR *xdrs, hamster_directory_arg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->fdptr))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->owner, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hamster, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hamster_directory_ret (XDR *xdrs, hamster_directory_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fdptr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hamster_howsdoing_ret (XDR *xdrs, hamster_howsdoing_ret *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->res))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->treats_left))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->rounds))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->cost))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->res);
			IXDR_PUT_SHORT(buf, objp->treats_left);
			IXDR_PUT_LONG(buf, objp->rounds);
			IXDR_PUT_SHORT(buf, objp->cost);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->res))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->treats_left))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->rounds))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->cost))
				 return FALSE;
		} else {
			objp->res = IXDR_GET_LONG(buf);
			objp->treats_left = IXDR_GET_SHORT(buf);
			objp->rounds = IXDR_GET_LONG(buf);
			objp->cost = IXDR_GET_SHORT(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->treats_left))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rounds))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->cost))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hamster_readentry_ret (XDR *xdrs, hamster_readentry_ret *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->owner, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hamster, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->price))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hamster_givetreats_arg (XDR *xdrs, hamster_givetreats_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ID))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->treats))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hamster_collect_arg (XDR *xdrs, hamster_collect_arg *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->owner, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
