/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hamster.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
hamster_rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		hamster_new_arg hamster_new_1_arg;
		hamster_lookup_arg hamster_lookup_1_arg;
		hamster_directory_arg hamster_directory_1_arg;
		int hamster_howsdoing_1_arg;
		int hamster_readentry_1_arg;
		hamster_givetreats_arg hamster_givetreats_1_arg;
		hamster_collect_arg hamster_collect_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case HAMSTER_NEW:
		_xdr_argument = (xdrproc_t) xdr_hamster_new_arg;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) hamster_new_1_svc;
		break;

	case HAMSTER_LOOKUP:
		_xdr_argument = (xdrproc_t) xdr_hamster_lookup_arg;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) hamster_lookup_1_svc;
		break;

	case HAMSTER_DIRECTORY:
		_xdr_argument = (xdrproc_t) xdr_hamster_directory_arg;
		_xdr_result = (xdrproc_t) xdr_hamster_directory_ret;
		local = (char *(*)(char *, struct svc_req *)) hamster_directory_1_svc;
		break;

	case HAMSTER_HOWSDOING:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_hamster_howsdoing_ret;
		local = (char *(*)(char *, struct svc_req *)) hamster_howsdoing_1_svc;
		break;

	case HAMSTER_READENTRY:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_hamster_readentry_ret;
		local = (char *(*)(char *, struct svc_req *)) hamster_readentry_1_svc;
		break;

	case HAMSTER_GIVETREATS:
		_xdr_argument = (xdrproc_t) xdr_hamster_givetreats_arg;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) hamster_givetreats_1_svc;
		break;

	case HAMSTER_COLLECT:
		_xdr_argument = (xdrproc_t) xdr_hamster_collect_arg;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) hamster_collect_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (HAMSTER_RPC, HAMSTER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, HAMSTER_RPC, HAMSTER, hamster_rpc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (HAMSTER_RPC, HAMSTER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, HAMSTER_RPC, HAMSTER, hamster_rpc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (HAMSTER_RPC, HAMSTER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
