/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hamster.h"
#include "../include/hamsterlib.h"


/**
 * @brief hmster_new rpc call
 * 
 * @param argp 
 * @param rqstp 
 * @return int* 
 */
int* hamster_new_1_svc(hamster_new_arg *argp, struct svc_req *rqstp) {
	static int result;
	result = hmstr_new(argp->owner, argp->hamster, argp->treats);
	return &result;
}

/**
 * @brief hmster_lookup rpc call
 * 
 * @param argp 
 * @param rqstp 
 * @return int* 
 */
int* hamster_lookup_1_svc(hamster_lookup_arg *argp, struct svc_req *rqstp) {
	static int result;

	result = hmstr_lookup(argp->owner, argp->hamster);

	return &result;
}

/**
 * @brief hmstr_directory rpc call
 * 
 * @param argp 
 * @param rqstp 
 * @return hamster_directory_ret* 
 */
hamster_directory_ret* hamster_directory_1_svc(hamster_directory_arg *argp,
								 struct svc_req *rqstp) {
	static hamster_directory_ret result;
	int fdptr = argp->fdptr;
	int res = hmstr_directory(&fdptr, strlen(argp->owner)==0?NULL:argp->owner,
								strlen(argp->hamster)==0?NULL:argp->hamster);
	result.res = res;
	result.fdptr = fdptr;
	return &result;
}

/**
 * @brief hmstr_howsdoing rpc call
 * 
 * @param argp 
 * @param rqstp 
 * @return hamster_howsdoing_ret* 
 */
hamster_howsdoing_ret* hamster_howsdoing_1_svc(int *argp, struct svc_req *rqstp) {
	static hamster_howsdoing_ret  result;
	struct hmstr_state state;
	
	int res = hmstr_howsdoing(*argp ,&state);
	
	result.res = res;
	result.cost = state.cost;
	result.rounds = state.rounds;
	result.treats_left = state.treats_left;
	return &result;
}

/**
 * @brief hmstr_readentry rpc call
 * 
 * @param argp 
 * @param rqstp 
 * @return hamster_readentry_ret* 
 */
hamster_readentry_ret* hamster_readentry_1_svc(int *argp, struct svc_req *rqstp) {
	static hamster_readentry_ret  result;
	
	result.res = hmstr_readentry(*argp,(char *)  &(result.owner),
								(char *)  &(result.hamster), &(result.price));

	return &result;
}

/**
 * @brief hmstr_givetreats rpc call
 * 
 * @param argp 
 * @param rqstp 
 * @return int* 
 */
int* hamster_givetreats_1_svc(hamster_givetreats_arg *argp, struct svc_req *rqstp) {
	static int  result;

	result = hmstr_givetreats(argp->ID, argp->treats);

	return &result;
}

/**
 * @brief hmstr_collect rpc call
 * 
 * @param argp 
 * @param rqstp 
 * @return int* 
 */
int* hamster_collect_1_svc(hamster_collect_arg *argp, struct svc_req *rqstp) {
	static int  result;
	result = hmstr_collect(argp->owner);

	return &result;
}
